### ISSUE TITLE
feat: HOUSEWORK INFO 삭제 API 구현

### ISSUE THREAD

**Issue by jusung-c** [ghdcksgml1/N-bbang-housework#104]
- HOUSEWORK INFO 테이블에서 삭제

**Comment by ghdcksgml1** [comment]
HouseworkInfo가 외래키로 등록되어있는 HouseworkTodo들의 외래키에 null 값 설정을 해줘야함.

+또한, HouseworkTodo의 HouseworkInfo가 사라졌을때 발생할 수 있는 사이드 이펙트 체크해야함

**Comment by jusung-c** [comment]
![IMG_78E29EDD94DC-1](https://github.com/ghdcksgml1/N-bbang-housework/assets/62228433/f5e1c0be-e586-4927-9cfd-aeed224559d8)

**Comment by ghdcksgml1** [comment]
1. HouseworkInfo를 외래키로 가지고 있는 HouseworkMember들 삭제
2. HouseworkInfo를 외래키로 가지고 있는 HouseworkTodo들의 houseworkInfos_id를 null로 변환
3. HouseworkInfo 삭제, **_삭제를 요청한 날짜를 기준으로 이후의 HouseworkTodo 들도 삭제 (?)_**

강조한 부분을 저렇게 처리하는게 맞을까요?
ex) 사용자가 2주 뒤에 날짜를 눌러보게 되면, 자동으로 HouseworkInfo 주기에 맞는 HouseworkTodo들이 생성됨. 
오늘 HouseworkInfo를 지운다고 하면, 2주 뒤에꺼를 미리 눌러본 HouseworkTodo가 남아있을텐데 이것을 지우는게 맞는지?

**Comment by ghdcksgml1** [comment]
HouseworkTodo에 상태 값인 HouseworkTodoStatus에 상태를 추가해 삭제된 집안일이라고 표시하는 방법도 있을 것 같습니다.

**Comment by jusung-c** [comment]
## API 시나리오
### **프론트**

<img width="280" alt="image" src="https://github.com/ghdcksgml1/N-bbang-housework/assets/62228433/e5a99f16-eadf-4be7-9d26-6cc58b2e5167"> <br/>

1. 삭제 버튼 클릭
2. HouseworkInfo Delete API 호출
    - groupId, date, todoId, allDelete를 JSON으로 요청

### ******************백엔드******************

******************Controller******************

- POST “housework/delete”
- 요청자 인증을 위한 Authorization 헤더에 담긴 토큰 필요
    - RequestHeader로 받기
- JSON을 받을 DTO 필요 → HouseworkInfoDeleteRequest
    - `Long groupId`
    - `LocalDate date`
    - `Long todoId`
    - `boolean allDelete`
        - 반복되는 모든 건 삭제하고 싶을 경우 true, 해당 건만 삭제하고 싶을 경우 false
- Authorization 토큰과 groupId로 Auth 서버에 인증 + 해당 그룹원이 맞는지 인증 요청

**Service**

- 집안일 삭제 권한이 있는지 확인
    - status: ACCEPT
- `HouseworkPeriodType`에 따른 처리
    - 먼저 받은 DTO의 todoId를 이용해 HouseworkTodo 조회해두기
        - HouseworkInfo 정보 필요하므로 fetchjoin해서 조회해두기
            - `findHouseworkTodoByIdJoinFetchHouseworkInfo`
    - **단건 집안일일 경우**
        1. HouseworkTodo의 상태를 DELETE로 변경
            - HouseworkTodo에 상태 수정 메서드 만들어서 구현
        2. groupInfoId와 date로 todoList를 조회 후 dirtyBit 체킹
    - **단건 외 집안일일 경우**
        - 해당 건만 삭제하고 싶을 경우 (DTO의 allDelete = false)
            1.  HouseworkTodo의 상태를 DELETE로 변경
        - 반복되는 건 모두 삭제하고 싶을 경우 (DTO의 allDelete = true)
            1. HouseworkInfo를 외래키로 가지고 있는 HouseworkMember들을 조회
            2. 조회한 HouseworkMember들은 삭제
                - 데이터 무결성 조건을 위해 HouseworkInfo보다 먼저 삭제해줘야 함
            3. HouseworkInfo를 외래키로 가지고 있는 HouseworkTodo들 조회
            4. 조회한 HouseworkTodo의 houseworkInfo를 null로 변환 (관계 해제)
            5. 조회한 HouseworkTodo들의 상태를 DELETE로 변경
            6. HouseworkInfo 삭제
