### ISSUE TITLE
feat: HOUSEWORK INFO 수정 API 구현

### ISSUE THREAD

**Issue by jusung-c** [ghdcksgml1/N-bbang-housework#105]
- [ ] 집안일 수정 API 구현
    - 단건 -> 비단건
    - 비단건 -> 단건
    - 비단건 -> 비단건
 
- [ ] 집안일 수정 API Test

**Comment by jusung-c** [comment]
### HOUSEWORK INFO 수정 가능한 필드

- 집안일 담당자
    - OneToMany
    - HouseworkMember 리스트
- 집안일 카테고리
    - ManyToOne
    - HouseworkCategory
- 집안일 제목
- 집안일 내용
- 집안일 주기 타입
- dayDate
- weekDate
- monthDate
- 집안일 마감시간

<hr/>

## API 시나리오

### **프론트**

1. 수정할 정보들 입력 후 수정 버튼 클릭
2. HouseworkInfo Update API 호출
    - PathVariable로 groupId를 넣어줌
    - 입력한 데이터를 JSON으로 RequestBody에 넣음
    
    ```json
    {
      "groupMemberIdList": ["1", "2", "3"],
      "houseworkCategory": "CLEANING",
      "title": "Clean the living room",
      "detail": "Dust, vacuum, and mop the living room.",
      "type": "HOUSEWORK_PERIOD_DAY",  
      "dayDate": "2023-11-10",
    	"weekDate": null,
    	"monthDate": null,
      "endTime": "18:00:00"
    }
    ```
    

### ******************백엔드******************

******************Controller******************

- POST “/houseworkInfo/update/{groupId}/{todoId}”
- 요청 JSON 데이터를 위한 DTO 필요
    - HouseworkAddRequestDTO
    - Requestbody로 받기
    - Valid로 유효성 검증
- 요청자 인증을 위한 Authorization 헤더에 담긴 토큰 필요
    - RequestHeader로 받기
- Authorization 토큰과 groupId로 Auth 서버에 인증 + 해당 그룹원이 맞는지 인증 요청

**Service**

- 집안일 수정 권한이 있는지 확인
    - status: ACCEPT
    - role: GROUP_ADMIN
- `HouseworkPeriodType`에 따른 처리
    - **단건 집안일 → 단건 외 집안일**
        1. url로 받은 todoId를 이용해 TodoList에서 삭제
        2. HouseworkMember 저장
        3. HouseworkInfo 저장 후 houseworkMember 담당자 지정
        4. 해당 그룹의 캐싱된 todoList 중 단건 외 타입을 필터링한 후  dirtyBit를 ture로 체킹
    - **단건 외 집안일 → 단건 집안일**
        1. HouseworkInfo 삭제
        2. HouseworkMember 저장
        3. HouseworkTodo 생성
            - groupInfoId와 Date로 todoList를 조회 후 캐싱되어있다면, dirtyBit를 true로 체킹
    - **단건 외 집안일 → 단건 외 집안일**
        1. HouseworkInfo 수정 메소드 사용해 수정
        2. 해당 그룹의 캐싱된 todoList 중 단건 외 타입을 필터링한 후  dirtyBit를 ture로 체킹

**Comment by jusung-c** [comment]
![houseworkUpdate 001](https://github.com/ghdcksgml1/N-bbang-housework/assets/62228433/ebcb7e64-2d25-40c7-8bae-aa420fa20211)

**Comment by ghdcksgml1** [comment]
> 단건 외 집안일 → 단건 집안일

이부분 HouseworkInfo 삭제하기 전에 기존 HouseworkTodo에 있던 의존성 다 끊어줘야합니다! null 값으로 대체

**Comment by jusung-c** [comment]
삭제 API와 동일하게 아래 과정 거치면 될까요?
1. HouseworkMember 삭제
2. HousewrokTodo 의존성 해제 후 DELETE 상태로 변환
3. HouseworkInfo 삭제

**Comment by ghdcksgml1** [comment]
네

**Comment by jusung-c** [comment]
<img width="348" alt="image" src="https://github.com/ghdcksgml1/N-bbang-housework/assets/62228433/1c21d695-c8d5-4f54-bd25-3bc38a855d95">

- 카테고리, 담당자, 집안일 주기 정보 등을 내려줄 때 어떻게 내려줘야 할지에 대한 고민
    - 해당 카테고리만 내려주는 방법
        - 재사용할 수 있을지도?
        - 카테고리 목록 조회 API 호출 후 해당 카테고리 조회 API 호출 (2번 호출)
    - 모든 카테고리 목록을 내려준 후 check 필드 추가해서 내려주는 방법
        - 한번의 호출로 끝
        - 나중에 재사용 할 일 없을 듯

**Comment by ghdcksgml1** [comment]
HouseworkTodo 아이디를 받으면 Todo에 딸린 INFO를 조인해서 데이터를 가져오면 모든 데이터를 다 넣어줄 수 있지 않나요??

**Comment by ghdcksgml1** [comment]
API를 2개 만들어 호출하는 것보단, Service 로직을 분리시키는게 더 나아보여요

**Comment by jusung-c** [comment]
기존 Todo 최대한 사용해보려고 했는데 굳이 그럴 필요가 없겠네요 리뷰감사합니다 😀

**Comment by ghdcksgml1** [comment]
제 말이 100% 다 맞는건 아니라서 하고싶은대로 해봐도 상관없긴 합니다! ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by jusung-c** [comment]
# API 시나리오

## 수정 화면 보여주기

### **프론트**

1. 수정 버튼 클릭
2. HouseworkInfo Update API GET으로 호출
    - header: authorization
    - path: groupId
    - param: date, todoId

### 백엔드

********************Controller********************

- GET “/housework/update/{groupId}”
- 요청자 인증을 위한 Authorization 헤더에 담긴 토큰 필요
    - RequestHeader로 받기
- DTO 필요 → HouseworkUpdateURLRequest
- Authorization 토큰과 groupId로 Auth 서버에 인증 + 해당 그룹원이 맞는지 인증 요청

**************Service**************

- todoId를 이용해 HouseworkTodo 조회
    - HouseworkInfo 정보 필요하므로 fetch join
        - HouseworkInfo가 null인 경우(단건 집안일)도 조회해줘야 하기 때문에 left join 사용
- **단건 집안일일 경우**
    - HouseworkTodo 정보 내려줌
- ******************************************************비단건 집안일일 경우******************************************************
    - HouseworkInfo 정보 내려줌

- **내려줄 DTO : HouseworkUpdateResponse**

<img width="172" alt="image" src="https://github.com/ghdcksgml1/N-bbang-housework/assets/62228433/234bd08f-cc21-4551-b23e-152f933051e8">

- `String title`
- `Long houseworkCategoryId`
- `List<Long> groupMemberIdList`
- `HouseworkPeriodType type`
- `LocalDate dayDate`
- `String weekDate`
- `String monthDate`
- `LocalTime endTime`

## 수정 API 시나리오

### 프론트

1. 수정 입력 폼 작성 후 수정 버튼 클릭
    - ${groupId}?todoId=${todoId}
    - body: 수정한 정보

******************Controller******************

- POST “/housework/update/{groupId}”
- 요청 데이터 받을 DTO 필요: HouseworkUpdateRequest
    - @PathVariable로 groupId 받기
    - @RequestParam으로 todoId 받기
    - @RequestBody로 DTO 받기 → @Valid 검증 필요
- Authorization 토큰과 groupId로 Auth 서버에 인증 + 해당 그룹원이 맞는지 인증 요청

**Service**

- groupId, todoId, requestDTO 보유
- todoId를 이용해 HouseworkTodo 조회
    - HouseworkInfo 정보 필요하므로 fetch join
        - HouseworkInfo가 null인 경우(단건 집안일)도 조회해줘야 하기 때문에 left join 사용
- groupId를 이용해 GroupInfo 조회
- **PeriodType에 따른 처리 → 집안일 생성, 삭제와 반복되는 로직 많으므로 메서드화 시켜서 재사용하기**
    - **단건 집안일**
        - **→ 단건 집안일**
            1. HouseworkTodo 수정 메소드 사용해 수정
            2. groupInfoId와 date로 todoList를 조회 후 캐싱되어있다면, dirtyBit를 true로 체킹
        - **→ 비단건 집안일**
            1. HouseworkTodo 삭제하기
                1. DELETE 상태로 변환
                2. 요청 날짜의 todoList를 조회 후 dirtyBit 체킹 
            2. HouseworkInfo 생성
                1. HouseworkCategory 조회
                2. HouseworkInfo 저장
                3. HouseworkMember 담당자 지정
                4. groupId로 todoList를 조회해서 Period로 필터링 후 dirtyBit 체킹
    - **비단건 집안일**
        - **→ 단건 집안일**
            1. HouseworkInfo 삭제하기
                1. HouseworkInfo를 외래키로 가진 HouseworkMember 삭제
                2. HouseworkInfo를 외래키로 가진 HouseworkTodo의 houseworkInfo 필드값 null로 변환해 관계 해제
                3. HouseworkInfo 삭제
                4. requestDate 이후의 HouseworkTodo를 HOUSEWORK_TODO_DELETE로 상태 변경
                5. groupId로 TodoList 조회하고 해당 requestTodo를 가진 TodoList로 필터링한 후 dirtyBit Checking
            2. HouseworkTodo 생성하기
                1. HouseworkTodo 생성
                2. 요청 날짜의 todoList를 조회 후 dirtyBit 체킹 
        - **→ 비단건 집안일**
            1. HouseworkInfo 수정하기
                1. HouseworkInfo 수정 메서드 사용해서 수정
                2. groupId로 todoList를 조회해서 Period로 필터링 후 dirtyBit 체킹
