### ISSUE TITLE
feat: 선물 조회 API 기능 개발 요청

### ISSUE THREAD

**Issue by ITKOO** [ghdcksgml1/N-bbang-housework#120]
<img width="298" alt="스크린샷 2023-11-22 오후 4 17 03" src="https://github.com/ghdcksgml1/N-bbang-housework/assets/31758135/9e7989c3-1791-44ca-9056-99c693d63125">

기프트샵 페이지에 보여질 데이터가 필요합니다.
필요한 데이터 항목은 아래와 같습니다.

- 선물 ID
- 이름
- 포인트 가격
- 이미지 url
- 상세설명

항상 빠른 처리 해주셔서 감사합니다 ㅎㅎ
확인부탁드려요!

**Comment by jusung-c** [comment]
### 해야할 일
- [x] 기프트샵 페이지에 보여주기만 할 상품 등록, 삭제, 조회할 수 있도록 + 상세 페이지 조회
- [ ] 실제 결제하는 부분은 맨 마지막에 시간 남으면 시도해볼게요


### ITEM


  | 필드 | 타입 | 설명 |  
-- | -- | -- | -- | --
PK | id | Long | Entity 고유 식별 값 | 자동 생성 전략
  | user | User | 상품 등록자 | ManyToOne
  | name | String | 상품 이름 |  
  | content | String | 상품 설명 |  
  | itemStatus | ItemStatus (Enum) | 상품 상태 | ITEM_AVAILABLE, ITEM_SOLE_OUT, ITEM_DELETED
  | itemImageURL | String | 상품 이미지 URL |  
  | profileImageUrl | String | 사용자 프로필 이미지 URL |  




### API
- ITEM 추가
- ITEM 삭제
- ITEM 리스트 조회
- ITEM 조회 (상세페이지)
