### ISSUE TITLE
도메인 서버 모듈 추가

### ISSUE THREAD

**Issue by ghdcksgml1** [ghdcksgml1/N-bbang-housework#61]
## 📍 도메인 서버 추가

- module naming : (미정)
- port : 8000
- prefix : /api/
- DB : MySQL, Redis

**Comment by ghdcksgml1** [comment]
### prefix 설정하는 이유

- nginx 설정할때 Prefix로 서버를 구분하기 때문
- 인증 서버 : /auth
- 알림 서버 : /notify
- 도메인 서버 : /api

**Comment by jusung-c** [comment]
1. heachi-core:housework-api
2. heachi-core:nbbang-api
3.

**Comment by ghdcksgml1** [comment]
housework로 진행하겠습니다~ ㅎㅎ
