### ISSUE TITLE
데이터베이스 설계 피드백 반영

### ISSUE THREAD

**Issue by ghdcksgml1** [ghdcksgml1/N-bbang-housework#67]
### USER 테이블 수정

- [x] groupList 
    - @OneToMany 연결
- [x] phoneNumber Unique 속성 추가
    - 중복회원가입 방지
- [x] UserRole - `WITHDRAWAL` 상태 추가
    - 회원 탈퇴시 상태 변경
- 재가입 시점에 이전 계정 platformId, email, phoneNumber 초기화할 예정

<br><br>

### GROUP_INFO 테이블 수정

- [x] gradient 필드 추가
    - 그룹의 CSS 속성 String으로 통째로 저장
    - ex) linear-gradient(to right, #ff8177 0%, #ff867a 0%, #ff8c7f 21%, #f99185 52%, #cf556c 78%, #b12a5b 100%)

<br><br>

### GROUP_BG 테이블 생성
- [x] Group color 관리 테이블 추가
    - bgColor
    - colorCode
    - gradient

<br><br>

### GROUP_MEMBER 테이블 수정
- [x] GroupMemberStatus에 `WITHDRAW` 상태 추가
    - 구성원이 그룹 탈퇴시 `WITHDRAW`로 상태 변경
- 그룹 탈퇴시 Todo 프로필을 탈퇴 프로필로 처리할 예정

<br><br>

### HOUSEWORK_PERIOD 테이블 삭제

- [x] HOUSEWORK_INFO 컬럼으로 병합

<br><br>

### HOUSEWORK_INFO 테이블 수정

- [x] HOUSEWORK_PEROID 컬럼 병합
- [x] `HOUSEWORK_PERIOD_MONTH` 타입 추가
    - PERIOD 타입에 따라 다르게 처리
        - `HOUSEWORK_PERIOD_DAY` → 날짜 (22.09.12, 22.11.03)
        - `HOUSEWORK_PERIOD_EVERYDAY` → 매일
        - `HOUSEWORK_PERIOD_WEEK` → 요일 (월, 화)
        - `HOUSEWORK_PERIOD_MONTH` → 일 (1, 23, 29)
- [x] HOUSEWORK_CATEGORY 연결 (@ManyToOne)

**HOUSEWORK_INFO 삭제 시나리오**
    - INFO가 단건인 경우: TODO 삭제시 같이 삭제
    - INFO가 단건이 아닌 경우: 현재 시점 이후의 INFO가 연결되어 있는 TODO 전부 삭제
    
<br><br>

### HOUSEWORK_TODO
- [x] 인증 관련 컬럼 필요
    - 인증 사진 url 컬럼 필요
    - 인증해준 사람 컬럼 필요
    - 인증해준 사람이 인증 버튼 누른 시간 컬럼 필요
- [x] 그룹 식별 정보 필요 **(+추가)**
    - 그룹 정보 식별 ➡️ groupInfo [@ManyToOne]
    - 날짜 정보 식별 ➡️ date
    - 위 두개의 정보들로 해당 날짜의 그룹의 TODO를 조회

**문제**

- INFO의 담당자(HOUSEWORK_MEMBER)가 변경되었을 경우 변경 시점 이후의 TODO를 모두 찾아서 집안일 담당자 필드(houseworkMember) 업데이트 필요
- category, title, detial 중 변경된 것이 있다면 업데이트 필요

******해결******

- [x] HOUSEWORK_INFO ID를 FK로 추가해서 @ManyToOne 관계 맺어준 후 INFO의 업데이트가 생기면 TODO도 같이 업데이트
    - 단, HOUSEWORK_PERIOD_DAY 가 아닐 때에만 참조

<br><br>

### HOUSEWORK_SAVE
- [x] GroupInfo로 검색할 수 있도록 인덱스 붙여주기
    - 인덱스 이름:  `HOUSEWORK_SAVE_GROUP_INFO_INDEX`

- 매일 자정 배치로 실행해 저장할 예정
    - 통용적으로 사용되는 집안일의 group_info_id는 null로 설정
    - 그룹에서 등록한 집안일은 group_info_id 존재

<br><br>

### Notify - MongoDB 테이블 수정
- [x] generateUrl 필드 삭제

<br><br>

### ERD mwb 파일 관리

- [ ] 깃허브에 DB 폴더 파서 mwb 파일 관리

**Comment by jusung-c** [comment]
### USER 테이블 수정

- [ ] groupList 필드 추가
    - @OneToMany 연결
- [ ] phoneNumber Unique 속성 추가
    - 중복회원가입 방지
- [ ] UserRole - `WITHDRAWAL` 상태 추가
    - 회원 탈퇴시 상태 변경
- 재가입 시점에 이전 계정 platformId, email, phoneNumber 초기화할 예정

<br><br>

### GROUP_INFO 테이블 수정

- [ ] gradient 필드 추가
    - 그룹의 CSS 속성 String으로 통째로 저장
    - ex) linear-gradient(to right, #ff8177 0%, #ff867a 0%, #ff8c7f 21%, #f99185 52%, #cf556c 78%, #b12a5b 100%)

<br><br>

### GROUP_BG 테이블 생성
- [ ] Group color 관리 테이블 추가
    - bgColor
    - colorCode
    - gradient

<br><br>

### GROUP_MEMBER 테이블 수정
- [ ] GroupMemberStatus에 `WITHDRAW` 상태 추가
    - 구성원이 그룹 탈퇴시 `WITHDRAW`로 상태 변경
- 그룹 탈퇴시 Todo 프로필을 탈퇴 프로필로 처리할 예정

<br><br>

### HOUSEWORK_PERIOD 테이블 삭제

- [ ] HOUSEWORK_INFO 컬럼으로 병합

<br><br>

### HOUSEWORK_INFO 테이블 수정

- [ ] HOUSEWORK_PEROID 컬럼 병합
** HOUSEWORK_INFO 삭제 시나리오**
    - INFO가 단건인 경우: TODO 삭제시 같이 삭제
    - INFO가 단건이 아닌 경우: 현재 시점 이후의 INFO가 연결되어 있는 TODO 전부 삭제
    
<br><br>

### HOUSEWORK_TODO
- [ ] 인증 관련 컬럼 필요
    - 인증 사진 url 컬럼 필요
    - 인증해준 사람 컬럼 필요
    - 인증해준 사람이 인증 버튼 누른 시간 컬럼 필요

**문제**

- INFO의 담당자(HOUSEWORK_MEMBER)가 변경되었을 경우 변경 시점 이후의 TODO를 모두 찾아서 집안일 담당자 필드(houseworkMember) 업데이트 필요
- category, title, detial 중 변경된 것이 있다면 업데이트 필요

******해결******

- [ ] HOUSEWORK_INFO ID를 FK로 추가해서 @ManyToOne 관계 맺어준 후 INFO의 업데이트가 생기면 TODO도 같이 업데이트

<br><br>

### HOUSEWORK_SAVE

- 매일 자정 배치로 실행해 저장할 예정
    - 통용적으로 사용되는 집안일의 group_info_id는 null로 설정
    - 그룹에서 등록한 집안일은 group_info_id 존재

<br><br>

### Notify - MongoDB 테이블 수정
- [ ] generateUrl 필드 삭제

<br><br>

### ERD mwb 파일 관리

- [ ] 깃허브에 DB 폴더 파서 mwb 파일 관리

**Comment by jusung-c** [comment]
![nbbang_erd](https://github.com/ghdcksgml1/N-bbang-housework/assets/62228433/79d5a0b9-a2aa-4e64-be89-91a970a7fb8c)
