### ISSUE TITLE
feat: 집안일 추가 

### ISSUE THREAD

**Issue by ghdcksgml1** [ghdcksgml1/N-bbang-housework#69]
## 📍 집안일 추가

- [ ] 시퀀스 다이어그램 작성하기
- [ ] 집안일 추가 창에서 조회해야할 데이터
- [ ] 집안일 담당자 할당하기
- [ ] 집안일 추가 버튼 눌렀을때

**Comment by jusung-c** [comment]
# 집안일 등록 시나리오

## 프론트

### 1. **집안일 정보 입력 후 할일 추가하기 버튼 클릭**

- 입력한 정보들이 올바른 형식의 데이터인지 확인

### 2 **. Housework Register API 호출**

- 사용자가 입력한 데이터 JSON 형식으로 API 호출
    
    ```json
    {
      "id": 1,
      "houseworkMembers": [
        {
          "id": 2,
          "houseworkInfo": {
            "id": 1
          },
          "groupMember": {
            "id": 3
          }
        }
      ],
      "houseworkCategory": {
        "id": 1,
        "name": "집안일"
      },
      "title": "거실 청소기 돌리기",
      "detail": "청소기로 거실 구석구석 돌려주세요.",
      "type": "HOUSEWORK_PERIOD_WEEK",
    	"dayDate": null,
      "weekDate": "0", 
    	"monthDate": null,
      "endTime": "20:00:00" 
    }
    ```
    

## 백엔드

### 3 **. HouseworkInfo Add API**

**Controller**

- POST `“/houseworkInfo/add”`
- 요청 JSON 데이터를 위한 DTO 필요
    - HouseworkAddRequestDTO
    - @RequestBody로 받기

**Service**

- 해당 그룹의 구성원인지 확인
    - 아닐 경우 예외 처리 필요
- 전달받은 DTO로 HouseworkInfo Build 후 DB에 저장
- 조회한 그룹 정보로 HouseworkSave Build 후 DB에 저장
- HouseworkAddResponseDTO Build 후 반환

**Comment by jusung-c** [comment]
<img width="907" alt="image" src="https://github.com/ghdcksgml1/N-bbang-housework/assets/62228433/652dd037-da05-4e19-9e27-46e396f9a0fe">

**Comment by jusung-c** [comment]
# 집안일 등록 시나리오

## 프론트

### 1. **집안일 정보 입력 후 할일 추가하기 버튼 클릭**

<img width="557" alt="image" src="https://github.com/ghdcksgml1/N-bbang-housework/assets/62228433/e1bab2dd-11c7-43e1-9894-de5816227f67">

- 입력한 정보들이 올바른 형식의 데이터인지 확인

### 2 **. Housework Register API 호출**

- 사용자가 입력한 데이터 JSON 형식으로 API 호출
    
    ```json
    {
      "groupMembers": [
        {
          "id": 1,
          "groupInfo": {
            "id": 100
          },
          "user": {
            "id": 200
          },
          "role": "GROUP_MEMBER",
          "status": "WAITING"
        },
        {
          "id": 2,
          "groupInfo": {
            "id": 101
          },
          "user": {
            "id": 201
          },
          "role": "ADMIN",
          "status": "ACCEPTED"
        }
      ],
      "houseworkCategory": "CLEANING",
      "title": "Clean the living room",
      "detail": "Dust, vacuum, and mop the living room.",
      "type": "DAILY",
      "dayDate": "2023-10-16",
      "weekDate": "0",
      "monthDate": "1",
      "endTime": "2023-10-16T18:00:00"
    }
    ```
    

## 백엔드

### 3 **. HouseworkInfo Add API**

**Controller**

- POST `“/houseworkInfo/add”`
- 요청 JSON 데이터를 위한 DTO 필요
    - HouseworkAddRequestDTO
    - @RequestBody로 받기
- 요청자 인증을 위한 Authorization 헤더에 담긴 토큰 필요
    - @RequestHeader로 받기

**Service**

- Auth 서버에 Refresh 토큰을 전송해 레디스에서 요청자 Email 정보 조회
- 해당 그룹의 구성원인지 확인 필요
    - 요청자가 그룹 구성원인지 판단
    - 아닐 경우 예외 처리 필요
- 집안일 추가 권한이 있는지 확인
    - status : ACCEPT
    - role: GROUP_ADMIN
    - 아닐 경우 예외 처리
- 전달받은 DTO로 HouseworkInfo Build
- 담당자 지정
    - HouseworkMember build 후 저장
        - HouseworkInfo 지정
- HouseworkSave Build 후 저장
- HouseworkAddResponseDTO 반환

**Comment by jusung-c** [comment]
<img width="764" alt="image" src="https://github.com/ghdcksgml1/N-bbang-housework/assets/62228433/8715758d-217d-4abe-9d73-b04809e6c2a0">

**Comment by ghdcksgml1** [comment]
유저 인증 부분은 해당 커밋 로그 땡겨서 써도 될 것 같아요 : https://github.com/ghdcksgml1/N-bbang-housework/commit/febb83a041b77fa1853195dbbf1befcd5f99534d

**Comment by jusung-c** [comment]
### 집안일 추가 로직 수정 버전

<img width="964" alt="image" src="https://github.com/ghdcksgml1/N-bbang-housework/assets/62228433/189c829c-c98b-441a-ac01-064c1abd3576">
