### ISSUE TITLE
feat: GROUP_MEMBER 조회

### ISSUE THREAD

**Issue by ghdcksgml1** [ghdcksgml1/N-bbang-housework#95]
HOUSEWORK_INFO를 생성할때 모든 GROUP_MEMBER들이 조회돼야한다. 
HOUSEWORK_MEMBER (집안일 담당자) 지정을 위해서

**Comment by jusung-c** [comment]
요 이슈의 요구사항을 잘 모르겠습니다 😢
GROUP_INFO를 생성할 때면 그룹장 User 정보를 가진 초기 상태이므로 그룹원은 그룹장 한명인 상태인 것으로 알고 있는데요.
GroupInfoController의 그룹 생성 API의 반환 객체로 GROUP_MEMBER 리스트, 즉 그룹장의 정보가 조회되어야 한다는 뜻일까요?

**Comment by ghdcksgml1** [comment]
죄송합니다. HOUSEWORK INFO 입니다...

**Comment by ghdcksgml1** [comment]
HOUSEWORK INFO에서 해당 집안일 담당자를 지정해줘야하는데 그때 멤버들을 조회해야해서 이 API가 필요해요 ㅎㅎ

**Comment by jusung-c** [comment]
### 기존의 HOUSEWORK_INFO 생성 과정 요약 (단건 집안일이 아닌 경우)

1. 생성할 HOUSEWORK_INFO의 담당자로 지정할 GROUP_MEMBER 리스트 조회
<img width="1127" alt="image" src="https://github.com/ghdcksgml1/N-bbang-housework/assets/62228433/d212edca-0e96-42fb-967e-5f78d3737857">

2. HOUSEWORK_INFO 생성
<img width="724" alt="image" src="https://github.com/ghdcksgml1/N-bbang-housework/assets/62228433/c24e5263-1e80-4372-923d-0d9a179f608e">

3. 조회한 GROUP_MEMBER 리스트를 HOUSEWORK_MEMBER로 저장
<img width="671" alt="image" src="https://github.com/ghdcksgml1/N-bbang-housework/assets/62228433/d4c26ec2-1c73-43fb-a4c4-334e65930b8f">

**Comment by jusung-c** [comment]
혹시 기존의 집안일 추가 과정이 비효율적이라 만드는 API일까요? 감을 잘 못잡겠어요 😓

**Comment by ghdcksgml1** [comment]
<img width="262" alt="스크린샷 2023-11-05 오후 3 18 05" src="https://github.com/ghdcksgml1/N-bbang-housework/assets/79779676/ed94fd71-17e0-496b-9453-4c3d854fad27">

HouseworkInfo를 생성하는 페이지에 들어갈때 해당 부분을 띄워주기 위해서는 GroupMember가 누군지 조회하는 과정이 필요합니다!

**Comment by jusung-c** [comment]
********************Controller********************

- GET 요청: “/group/info/{groupId}/members”
    - groupId를 PathVariable로 받기
- groupId로 상태가 ACCEPT인 GROUP_MEMBER 리스트 조회
- GroupMemberListResponse DTO 반환
    - 그룹 멤버의 User의 username 필드
        - 화면에 띄워줄 이름
    - 그룹 멤버 Id 필드
        - HOUSEWORK INFO 생성시에 필요한 Id

**Comment by ghdcksgml1** [comment]
groupInfo와는 관련이 없는 작업이기 때문에
url : /group/member/{groupId}로 가는 맞을 것 같아요

**Comment by jusung-c** [comment]
아 그러면 GroupInfoController 말구
GroupMemberController를 따로 만들어서 구현하는 게 좋을까요?

**Comment by ghdcksgml1** [comment]
> 아 그러면 GroupInfoController 말구
> 
> GroupMemberController를 따로 만들어서 구현하는 게 좋을까요?

네!

**Comment by jusung-c** [comment]
********************Controller - GroupMemberController********************

- GET 요청: “/group/member/{groupId}”
    - groupId를 PathVariable로 받기
- API 호출자가 해당 그룹원인지 권한 체크
    - 인증을 위한 Authorization 헤더 정보 필요
- groupId로 상태가 ACCEPT인 GROUP_MEMBER 리스트 조회
- GroupMemberListResponse DTO 반환
    - 그룹 멤버의 User의 username 필드
        - 화면에 띄워줄 이름
    - 그룹 멤버 Id 필드
        - HOUSEWORK INFO 생성시에 필요한 Id
